// The snapshot bakes the extension ESM (see build.rs) so user workers restore
// the runtime instead of rebuilding it per spawn. build.rs mirrors the
// feature-gated trex_core ext (cfg(feature = "trex")) so `trex`-feature builds
// restore the same extension list and avoid ExtensionSnapshotMismatch.
pub static CLI_SNAPSHOT: &[u8] =
  include_bytes!(concat!(env!("OUT_DIR"), "/RUNTIME_SNAPSHOT.bin"));

pub fn snapshot() -> Option<&'static [u8]> {
  Some(CLI_SNAPSHOT)
}

/// NOTE(deno-2.9.5): `(specifier, source)` pairs for every `lazy_loaded_js` /
/// `lazy_loaded_esm` file that snapshot-time evaluation did *not* consume.
/// deno_core stores empty bytes for those in the snapshot blob and expects the
/// embedder to ship them alongside; without these tables anything loaded on
/// demand (the whole `node:*` polyfill closure included) fails with "cannot be
/// lazy-loaded as it was not included in the binary". Generated by build.rs.
mod residual {
  include!(concat!(env!("OUT_DIR"), "/EXTENSION_RESIDUAL_SOURCES.rs"));
}

pub use residual::RESIDUAL_LAZY_ESM;
pub use residual::RESIDUAL_LAZY_JS;
